# ___ __   __   ___
#  | /  \ |__) |__  \_/
#  | \__/ |  \ |___ / \

# Настройки TG API
longpoll:
  # Токен доступа
  token: TOKEN

# Отправка сообщений
messages:
  # Шанс генерации текста
  chance: 100
  # Максимальное кол-во символов в тексте
  # * Если символов в тексте будет больше данного значения сообщение не отправится
  symbols_limit: 250
  # ID бесед, в которых бот активен
  # Чтобы бот работал везде поставьте значение <<all>>
  active_chats: all
  # Форматирование текста
  format: false
  # Имитация набора текста
  writing_imitation: true

# Генерация текста
generation:
  # Минимальное кол-во слов в генерируемом тексте
  min_words: 5

# Настройки БД
database:
  # Сохранение сообщений пользователей
  # * Одинаковые строки не сохраняются
  data_save: true